spring.application.name=PromSafe

spring.datasource.url=jdbc:postgresql://localhost:5432/prom_safe
spring.datasource.username=postgres
spring.datasource.password=1234

spring.datasource.hikari.maximum-pool-size=8

app.questionsAmtGroup3=10
app.questionsAmtGroup4=20
